/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["var(--font-family-sans)", "system-ui", "sans-serif"],
        mono: ["var(--font-family-mono)", "monospace"],
      },
      colors: {
        primary: "var(--color-primary)",
        "primary-hover": "var(--color-primary-hover)",
        "primary-active": "var(--color-primary-active)",
        "primary-muted": "var(--color-primary-muted)",
        accent: "var(--color-accent)",
        "accent-hover": "var(--color-accent-hover)",
        "accent-subtle": "var(--color-accent-subtle)",
        "accent-muted": "var(--color-accent-muted)",
        background: "var(--color-background)",
        surface: "var(--color-surface)",
        "surface-raised": "var(--color-surface-raised)",
        "surface-sunken": "var(--color-surface-sunken)",
        border: "var(--color-border)",
        "border-subtle": "var(--color-border-subtle)",
        "border-strong": "var(--color-border-strong)",
        foreground: "var(--color-text)",
        muted: "var(--color-text-secondary)",
        subtle: "var(--color-text-tertiary)",
        success: "var(--color-success)",
        "success-subtle": "var(--color-success-subtle)",
        warning: "var(--color-warning)",
        "warning-subtle": "var(--color-warning-subtle)",
        error: "var(--color-error)",
        "error-subtle": "var(--color-error-subtle)",
        info: "var(--color-info)",
        "info-subtle": "var(--color-info-subtle)",

        // Legacy jea-* aliases
        "jea-navy": "var(--color-primary)",
        "jea-navy-mid": "var(--color-primary-hover)",
        "jea-navy-soft": "var(--color-primary-muted)",
        "jea-cyan": "var(--color-accent)",
        "jea-cyan-light": "var(--color-accent-subtle)",
        "jea-cyan-muted": "var(--color-accent-muted)",
        "jea-bg": "var(--color-background)",
        "jea-surface": "var(--color-surface)",
        "jea-border": "var(--color-border)",
        "jea-border-soft": "var(--color-border-subtle)",
        "jea-text": "var(--color-text)",
        "jea-text-muted": "var(--color-text-secondary)",
        "jea-text-subtle": "var(--color-text-tertiary)",
        "jea-success": "var(--color-success)",
        "jea-success-bg": "var(--color-success-subtle)",
        "jea-warning": "var(--color-warning)",
        "jea-warning-bg": "var(--color-warning-subtle)",
        "jea-danger": "var(--color-error)",
        "jea-danger-bg": "var(--color-error-subtle)",
        "jea-info": "var(--color-info)",
        "jea-info-bg": "var(--color-info-subtle)",
      },
      boxShadow: {
        "jea-sm": "var(--shadow-sm)",
        "jea-md": "var(--shadow-md)",
        "jea-lg": "var(--shadow-lg)",
      },
      borderRadius: {
        "jea-sm": "var(--radius-sm)",
        "jea-md": "var(--radius-md)",
        "jea-lg": "var(--radius-lg)",
        "jea-xl": "var(--radius-xl)",
      },
    },
  },
  plugins: [],
}
